# All of these can be overriden with environment variables of the same name

# default Alpine base image version
ALPINE_VERSION ?= 3.10

# default version of ISC Kea
KEA_VERSION ?= 1.6.0

# default prefix
KEA_INSTALLPREFIX ?= /usr/local

# default compiling jobs for building kea inside the docker
MAKE_JOBS ?= 4

# docker image tag
IKEA_TAG ?= ikea

# name of the saved docker image (tar)
IKEA_IMG ?= ikea-image

# package name
IKEA_PKG ?= ikea

# build directory
BUILD_DIR ?= build

# by default delete the work directory (compiled files)
KEEP_BUILDBLOB ?= no

# by default delete packages not needed for runtime
KEEP_BUILDDEPS ?= no

# build and install hooks (for the relevant kea version)
INSTALL_HOOKS ?= yes
