# All of these can be overriden with environment variables of the same name

# default version of ISC Kea
KEA_VERSION ?= 1.6.0

# default prefix
KEA_INSTALLPREFIX ?= /usr/local

# default compiling jobs for building kea inside the docker
MAKE_JOBS ?= 4

# docker image tag
IKEA_TAG ?= ikea

# name of the saved docker image (tar)
IKEA_IMG ?= ikea-image

# package name
IKEA_PKG ?= ikea

# build directory
BUILD_DIR ?= build
